### ISSUE TITLE
IO Exception

### ISSUE THREAD

**Issue by 8debug** [shrhdk/theta4j#4]
Thanks for your code.
I have a DSLR, I run the your code...It have a IO Exception when I connect my dslr with wireless.

**Comment by shrhdk** [comment]
Thank you for trying 👍 

`IOException` is general exception in Java. Could you give me a stacktrace of the exception?

**Comment by 8debug** [comment]
device: nikon d5300

I want get photos with wireless

![1487059603 1](https://cloud.githubusercontent.com/assets/3394927/22920423/f35227c4-f2cf-11e6-8f79-d3f643b6b5de.jpg)

Thank you very much

**Comment by shrhdk** [comment]
@297179121 Thank you for more information.

It faces unexpected TCP session termination while receiving the response of OpenSession Command. theta4j sends some commands before OpenSession command, and those commands are working.

I found the PTP/IP library [mmattes/ptpip](https://github.com/mmattes/ptpip) tested on D5300.

I read it and found the difference between mmattes/ptpip and theta4j. mmattes/ptpip uses connection number as session ID. I don't know why, but so. theta4j is using constant `1` as sessiond ID.

I built theta4j which is using connection number as session ID. Please try it.

- [theta4j-0.5.0.zip](https://github.com/shrhdk/theta4j/files/799864/theta4j-0.5.0.zip) (Please rename to `theta4j-0.5.0.jar`)
- https://github.com/shrhdk/theta4j/tree/trying-d5300

**Comment by pjt33** [comment]
I'm also trying to build a working connection to a Nikon D5300. I'm using the trying-d5300 branch (haven't tested with main).

The first error I got was

    java.io.IOException: Unexpected packet length: Actual=6, Expected=26.
     at org.theta4j.ptpip.packet.PtpIpPacketUtils.checkLength
     at org.theta4j.ptpip.packet.OperationResponsePacket.read
     at org.theta4j.ptpip.io.PtpIpInputStream.readOperationResponsePacket
     at org.theta4j.ptpip.PtpIpInitiator.receiveResponse
     at org.theta4j.ptp.AbstractPtpInitiator.checkAndReadResponse
     at org.theta4j.ptp.AbstractPtpInitiator.openSession
     at org.theta4j.Theta.<init>

This seems to be that the D5300 abbreviates the packet by omitting trailing zero parameters. I hacked `OperationResponsePacket.read` to handle payloads of 6, 10, 14, 18, 22, or 26 bytes, and then the next error I get is

    org.theta4j.ptp.PtpException: ResponseCode was not OK: 0x2006
     at org.theta4j.ptp.AbstractPtpInitiator.checkAndReadResponse(AbstractPtpInitiator.java:260)
     at org.theta4j.ptp.AbstractPtpInitiator.openSession(AbstractPtpInitiator.java:100)
     at org.theta4j.Theta.<init>(Theta.java:79)

`0x2006` is

> ### Parameter Not Supported
>
> ResponseCode: 0x2006  
> Desc: Indicates that a non-zero parameter was specified in conjunction with the operation, and that parameter is not used for that operation.

The obvious thing was to look at the request packet that was being sent. And here is where I get very confused.

>             this.payload = ArrayUtils.join(
>                     dataPhaseInfo.bytes(),
>                     operationCode.bytes(),
>                     transactionID.bytes(),
>                     p1.bytes(),
>                     p2.bytes(),
>                     p3.bytes(),
>                     p4.bytes(),
>                     p5.bytes()
>             );

But the PTP specification says that the structure of an `OperationRequest` dataset is

    OperationCode 2 UINT16
    SessionID     4 UINT32
    TransactionID 4 UINT32
    Parameter1    4 Any
    Parameter2    4 Any
    Parameter3    4 Any
    Parameter4    4 Any
    Parameter5    4 Any

So at this point I think I should take a break for a sanity check and ask whether you can explain what seems to me to make no sense. Where did `dataPhaseInfo` come from? What happened to `SessionID`?

Edit: ah, I was being stupid not to realise that the session ID is largely irrelevant since the IP layer does the job. So `dataPhaseId` is gphoto's [PTP/IP reverse engineering](http://gphoto.org/doc/ptpip.php) "4 byte unknown. set to 1 currently". I'll see whether trimming trailing zeroes from the request packet helps...

Edit 2: bingo, that works. So the question is: presumably the Ricoh Theta expects to receive the "excess" parameters. Do you want me to make a PR so that you can test the "trimmed" packets with the Theta, or jump straight to having a global flag to trim or not? If the latter, do you have any preference for how to inject it? Or would you rather take that description of the changes and structure the changes in your own way?

**Comment by pjt33** [comment]
Ok, it turns out that Nikon has more quirks. It doesn't use the event connection (nor even respond to ProbeRequest packets): it just closes it. It's necessary to poll for events with operation code 0x90C7.
